Added a tornado-tilestache example
OpenGeoscience/KTile pull request #4
Opened 2016-10-14 18:53 UTC by dorukozturk

@aashish24 PTAL

2016-10-14 20:45 UTC, aashish24 commented
great! can you add a readme on how to setup tornado (or a pointer to some document)?

2016-10-20 14:20 UTC, dorukozturk commented
@aashish24 I added some instructions. PTAL

2016-10-24 15:43 UTC, aashish24 commented
thanks @dorukozturk I see the image but I also seeing this error: 

Traceback (most recent call last):
  File "/home/chaudhary/tools/tilestache/src.git/tilestache_dev/local/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "server.py", line 76, in get
    layer_name, z, x, y = components
ValueError: need more than 1 value to unpack

2016-10-24 16:07 UTC, dorukozturk commented
@aashish24 The browser is sending one extra request when the page is first loaded. 
The request is to get the favicon. I can do a try except block or add a favicon. I will fix this.

2016-10-24 16:33 UTC, dorukozturk commented
@aashish24 https://github.com/OpenGeoscience/KTile/pull/4/commits/ab9d89da9ac77207aa3f9e420b45a3502d91f348 Attempts to fix this.

2016-10-24 16:35 UTC, aashish24 commented
thanks its better but may not be not totally removed. Also, can you address style issues?

I am getting this now: 
(dev)[chaudhary@einstein tornado (tornado-example)]$ python server.py 
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.09ms

2016-10-24 16:38 UTC, aashish24 requested changes

2016-10-24 16:38 UTC, aashish24 commented on examples/tornado/server.py
> +import TileStache
could you please have a space between these two groups as python convention?

2016-10-24 16:38 UTC, aashish24 commented on examples/tornado/server.py
> +<?xml version="1.0" encoding="utf-8"?>
can we indent it?

2016-10-24 16:38 UTC, aashish24 commented on examples/tornado/server.py
> +
Nitpick: Is this convention to leave a whitespace after the signature? I typically see that if you have documentation.

2016-10-24 16:38 UTC, aashish24 commented on examples/tornado/server.py
> +        status_code, headers, content = TileStache.requestHandler2(config, path_info)
@dorukozturk do we always has to pass config?

2016-10-25 16:31 UTC, aashish24 commented
@dorukozturk I pushed a change, have a look and let me know if you have any suggestions. I will add some docs and bit more optimization and then will call it done.

2016-10-27 03:11 UTC, merged